{
 "title": "Application Metrics",
 "panels": [
  {
   "title": "Application TPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=~\"/api/(fast|slow)-response\"}[1m])"
    }
   ]
  },
  {
   "title": "Response Delay (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri=~\"/api/(fast|slow)-response\"}[5m])) by (le, uri)) * 1000"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "jvm_threads_live_threads" }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[5m]) * 1000"
    }
   ]
  }
 ]
}