{
 "title": "Gatling Metrics",
 "templating": {
  "list": [
   { "name": "DS_GATLING", "label": "Data Source", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Gatling TPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "/^gatling\\..*\\.allRequests\\.all\\.count$/",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "measurement": "/^gatling\\..*\\.allRequests\\.all\\.percentiles95$/",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "measurement": "/^gatling\\..*\\.allRequests\\.ok\\.count$/",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    },
    {
     "measurement": "/^gatling\\..*\\.allRequests\\.all\\.count$/",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    },
    { "type": "math", "expression": "100 * $A / $B" }
   ]
  },
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "measurement": "/^gatling\\..*\\.allRequests\\.ko\\.count$/",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ],
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ]
    }
   ]
  }
 ]
}